### ISSUE TITLE
Latest doesn't compile with arm-linux-gnueabihf-gcc-10.2.0 (GCC) 10.2.0

### ISSUE THREAD

**Issue by ronaaron** [smuellerDD/jitterentropy-library#208]
I'm using that compile to cross-compile for Raspberry Pi 32-bit, and now I'm getting:

```
In file included from src/jitterentropy.h:87,
                 from src/jitter.c:2:
src/arch/jitterentropy-arch-ncpu.h:101:13: error: declaration of ‘long int syscall(long int, ...)’ has a different exception specifier
  101 | extern long syscall(long number, ...);
      |             ^~~~~~~
In file included from src/jitterentropy.h:67,
                 from src/jitter.c:2:
/clear/rpi32root/usr/include/unistd.h:1056:17: note: from previous declaration ‘long int syscall(long int, ...) throw ()’
 1056 | extern long int syscall (long int __sysno, ...) __THROW;
      |                 ^~~~~~~
make: [makefile:926: bin/rpi32/2/jitter.o] Error 1 (ignored)

```

**Comment by smuellerDD** [comment]
Am Dienstag, 19. Mai 2026, 06:56:16 Mitteleuropäische Sommerzeit schrieb 
ronaaron:

Hi ronaaron,

Can you please check whether the following patch would fix the issue?

diff --git a/arch/jitterentropy-arch-ncpu.h b/arch/jitterentropy-arch-ncpu.h
index c1b87c556c49..199d06d8d0a5 100644
--- a/arch/jitterentropy-arch-ncpu.h
+++ b/arch/jitterentropy-arch-ncpu.h
@@ -98,7 +98,7 @@
  * which hides it. The libc-agnostic signature below matches both glibc
  * and musl and avoids polluting the wider compile with _GNU_SOURCE.
  */
-extern long syscall(long number, ...);
+extern long syscall(long number, ...) __THROW;
 #  ifndef __GLIBC__
 #   include <fcntl.h>
 #   include <stdlib.h>

Thanks

Ciao
Stephan

**Comment by ronaaron** [comment]
Yes, that fixes it.

**Comment by smuellerDD** [comment]
Applied, thanks.

**Comment by ronaaron** [comment]
I'm sorry to say, but the  Android NDK  clang (18) complains about the __THROW:

```
In file included from src/jitterentropy.h:87:
src/arch/jitterentropy-arch-ncpu.h:101:39: error: expected function body after function declarator
  101 | extern long syscall(long number, ..make: *** [makefile:906: bin/android64/2/jitterentropy-gcd.o] Error 1
.) __THROW;
~~~

**Comment by smuellerDD** [comment]
Am Mittwoch, 20. Mai 2026, 14:57:13 Mitteleuropäische Sommerzeit schrieb 
ronaaron:

Hi ronaaron,

> ronaaron left a comment (smuellerDD/jitterentropy-library#208)
> 
> I'm sorry to say, but the  Android NDK  clang (18) complains about the
> __THROW:

Thanks a lot for testing. Stay tuned.

Ciao
Stephan

**Comment by ronaaron** [comment]
Still issues w android
```
In file included from src/jitterentropy-status.c:20:
In file included from src/jitterentropy.h:92:
src/arch/jitterentropy-arch-ncpu.h:169:31: error: call to undeclared function 'CPU_ALLOC_SIZE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  169 |                 size_t cpu_set_alloc_size = CPU_ALLOC_SIZE(CPU_SETSIZE);
```

**Comment by thillux** [comment]
Hi @ronaaron,

I was not able to reproduce this with a recent NDK. This function/macro is not available, when the _GNU_SOURCE definition in jitterentropy.h has no effect in arch/jitterentropy-arch-ncpu.h. Do you copy the source code into a custom build and have not updated jitterentropy.h? You may also need to define _GNU_SOURCE on the top of the file including jitterentropy.h.

BR
Markus

**Comment by ronaaron** [comment]
I just updated from NDK 27c to 29, am using the toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi35-clang
and double-checked I've got the same jitterentropy code in my project as here.

Still get
~~~
jitterentropy-arch-ncpu.h:169:31:: error:  call to undeclared function 'CPU_ALLOC_SIZE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
~~~

**Comment by thillux** [comment]
In order for me to reproduce this:
* Do you build with make or cmake?

**Comment by ronaaron** [comment]
I only use make.

**Comment by thillux** [comment]
Can you test with cmake, as that already works on my side?

**Comment by ronaaron** [comment]
No, my build system is very complex and porting to cmake is not something I would even attempt.

**Comment by thillux** [comment]
I can't reproduce the issue so far. I'm able to build with make and target Armv7a and Aarch64 for NDK-based builds on my NixOS machine. Can you help with a small reproducer based on Debian or so (as I probably cannot find your build code as open source on Github?)?

**Comment by ronaaron** [comment]
Maybe it's some issue with CFLAGS? I'll try to make a small repro case.

**Comment by ronaaron** [comment]
oof. I figured it out.

The *actual* problem was that I compiled some of the files with an "-include" directive including some local header which was harmful in this instance. So ... never mind, and thanks for your patience.

**Comment by thillux** [comment]
Ok, no worries. Thanks for reporting back, so that I can close this in my mind :)
