### PR TITLE
Makefile: add ENABLE_STACK_PROTECTOR

### PR DESCRIPTION
**Pull request by ffontaine**
Add `ENABLE_STACK_PROTECTOR` as build on embedded toolchains without stack-protector is again broken since https://github.com/smuellerDD/jitterentropy-library/commit/5b3cb7f35e41ba2f34a75d004cf095c965a1a0c4:

```
/home/buildroot/autobuild/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/i686-buildroot-linux-uclibc/9.3.0/../../../../i686-buildroot-linux-uclibc/bin/ld: src/jitterentropy-base.o: in function `jent_fips_enabled':
jitterentropy-base.c:(.text+0x131): undefined reference to `__stack_chk_fail_local'
```

Fixes:
 - http://autobuild.buildroot.org/results/8dee462d16d934dd173d58f17933c6911e4336bf

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by smuellerDD** [comment]
Applied, thanks.
